import { statusView } from "../../ui/status-view.js";
const states={loading:{eyebrow:"One moment",title:"Lighting your path…",message:"We are gathering this part of your journey."},empty:{eyebrow:"A quiet beginning",title:"Nothing is here yet.",message:"When your journey grows, its next step will appear here.",action:{label:"Discover experiences",href:"#/discover"}},error:{eyebrow:"Something interrupted the path",title:"We could not load this page.",message:"Please try again, or return to Discover.",action:{label:"Return to Discover",href:"#/discover"}},offline:{eyebrow:"You appear to be offline",title:"The path will wait for you.",message:"Reconnect to the internet and try again.",action:{label:"Try again",href:"#/discover"}},"not-found":{eyebrow:"Page not found",title:"This path is yet to be illuminated.",message:"Return to Discover to continue your My Gita journey.",action:{label:"Go to Discover",href:"#/discover"}}};
export function systemPage(type){return statusView(states[type]||states["not-found"]);}

export function reviewPage(){const groups=[
  ["Discover & experiences",[["Discover","#/discover"],["Gita for Children","#/experience/gita-for-children"],["Gita Sāra","#/experience/gita-sara"],["Choose batch","#/experience/gita-sara/enrol"],["Register interest","#/experience/purna-yoga-darsana/enrol"]]],
  ["Authentication",[["Choose sign-in method","#/auth"],["Mobile number","#/auth/mobile"],["OTP","#/auth/otp"],["Onboarding","#/onboarding"]]],
  ["Journey & profile",[["My Journey","#/journey"],["Activity detail","#/activity/activity-sara-teaching"],["Activity session","#/activity/activity-sara-teaching/session"],["Profile","#/profile"]]],
  ["System states",[["Loading","#/states/loading"],["Empty","#/states/empty"],["Error","#/states/error"],["Offline","#/states/offline"],["Not found","#/unknown"]]]
];return `<section class="review-page"><p class="eyebrow">Phase 1 review</p><h1>Screen map</h1><p>Open every distinct fixture-driven screen from one place.</p><div class="review-grid">${groups.map(([title,links])=>`<section class="panel"><h2>${title}</h2><ul>${links.map(([label,href])=>`<li><a href="${href}">${label}</a></li>`).join("")}</ul></section>`).join("")}</div><button class="button button--secondary" type="button" data-action="reset-fixtures">Reset prototype state</button></section>`;}
