// @ts-check
import { button } from "../core/ui/button.js";
import { passwordField, profileEditor, usernameField } from "../features/identity/index.js";

export function signInPage(){return `<section class="auth-page"><div class="dipa" aria-hidden="true"><span>दी</span><i></i></div><div class="auth-panel panel"><p class="eyebrow">Welcome back</p><h1>Sign in to MyGita</h1><p>Continue with your experiences and learning journey.</p><form class="form-grid" data-form="password-login">${usernameField()}${passwordField("password","Password","current-password")}<p class="form-error" data-form-error role="alert" hidden></p>${button({label:"Sign in",type:"submit"})}</form><p class="auth-alternative">New to MyGita? <a class="text-link" href="#/auth/create">Create an account</a></p><details class="prototype-auth"><summary>Prototype sign-in option</summary><a href="#/auth/mobile">Continue with mobile OTP</a></details></div></section>`;}

export function createAccountPage(){return `<section class="auth-step panel"><p class="eyebrow">Your MyGita space</p><h1>Create an account</h1><p>Create a private place to join experiences and continue your learning. Mobile number and email are not required.</p><form class="form-grid" data-form="password-account">${usernameField({label:"Choose a username",withHelp:true})}${passwordField("password","Create a password","new-password","Use a memorable phrase of at least 15 characters.")}${passwordField("confirmPassword","Confirm password","new-password")}<p class="form-error" data-form-error role="alert" hidden></p>${button({label:"Create my account",type:"submit"})}</form><p class="auth-alternative">Already have an account? <a class="text-link" href="#/auth">Sign in</a></p></section>`;}

export const authMethodsPage=signInPage;
export function mobilePage(){return `<section class="auth-step panel"><p class="eyebrow">Sign up or sign in</p><h1>Your mobile number</h1><p>We’ll send a one-time password. The country code is fixed for this prototype.</p><form class="form-grid" data-form="mobile"><div class="mobile-field"><span aria-label="Country code">+91</span><label class="visually-hidden" for="mobile">Mobile number</label><input id="mobile" name="mobile" inputmode="numeric" pattern="[6-9][0-9]{9}" maxlength="10" placeholder="98765 43210" required></div><p class="form-error" data-form-error hidden></p>${button({label:"Send OTP",type:"submit"})}</form></section>`;}
export function otpPage(mobile=""){return `<section class="auth-step panel"><p class="eyebrow">Check your messages</p><h1>Enter the 6-digit OTP</h1><p>Sent to +91 ${mobile||"your mobile"}. For this prototype, use <strong>123456</strong>.</p><form class="form-grid" data-form="otp"><label class="field"><span class="field__label">One-time password</span><input name="otp" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" placeholder="123456" required></label><p class="form-error" data-form-error hidden></p>${button({label:"Verify and continue",type:"submit"})}</form></section>`;}
export function onboardingPage(profile={}){return profileEditor(profile,{afterRegistration:true});}
