// @ts-check
import { escapeHtml } from "../core/dom.js";
import { button } from "../core/ui/button.js";
import { pill } from "../core/ui/pill.js";
import { statusView } from "../core/components/status-view.js";
import { experienceRepository } from "../features/experience/index.js";

export async function enrolPage(slug){const item=await experienceRepository.getExperience(slug);if(!item)return null;const batches=await experienceRepository.getBatches(item.id);if(!item.delivery.requiresBatch)return `<section class="narrow-page panel"><p class="eyebrow">Stay connected</p><h1>Register interest in ${escapeHtml(item.title)}</h1><p>We will let you know when the next guided journey opens.</p><form data-form="interest" data-experience="${item.id}" data-slug="${item.slug}">${button({label:"Register my interest",type:"submit"})}</form></section>`;return `<section class="narrow-page"><a class="back-link" href="#/experience/${item.slug}">← ${escapeHtml(item.title)}</a><p class="eyebrow">Choose a batch</p><h1>When would you like to begin?</h1><form class="batch-list" data-form="enrol" data-experience="${item.id}" data-slug="${item.slug}">${batches.map((batch,index)=>`<label class="batch-option"><input type="radio" name="batchId" value="${batch.id}" ${index===0?"checked":""}><span><strong>${escapeHtml(batch.name)}</strong><small>${escapeHtml(batch.period)} · ${escapeHtml(batch.time)}</small></span>${pill("Open")}</label>`).join("")}${button({label:"Confirm this batch",type:"submit"})}</form></section>`;}
export async function confirmationPage(slug,type){const item=await experienceRepository.getExperience(slug);const interest=type==="interest";return statusView({eyebrow:interest?"Interest registered":"You are enrolled",title:interest?"We’ll keep the lamp lit.":"Your journey begins here.",message:interest?`We will notify you when ${item?.title||"this experience"} opens.`:`${item?.title||"This experience"} is now part of My Journey.`,action:{label:interest?"Continue discovering":"Open My Journey",href:interest?"#/discover":"#/journey"}});}
